/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessNewPet': EventHandler<never, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'PatchPet': ApiRouteHandler<{ name?: string; photoUrl?: string }, ApiResponse<200, { id: string; name: string; photoUrl: string }> | ApiResponse<404, { message: string }>, never>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ListPets': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, Array<{ id: string; name: string; photoUrl: string }>>, never>
    'ListPetsOnCreate': EventHandler<never, never>
    'GetPet': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; name: string; photoUrl: string }> | ApiResponse<404, { message: string }>, never>
    'DeletePet': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message?: string }> | ApiResponse<404, { message: string }>, never>
    'DeleteAllPets': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message?: string }> | ApiResponse<404, { message: string }>, never>
    'CreatePet': ApiRouteHandler<{ name: string; photoUrl: string }, ApiResponse<201, { id: string; name: string; photoUrl: string }>, { topic: 'pet.created'; data: never }>
  }
    
}